[package]
name = "meter-rs"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
anyhow = "1.0.102"
slint = { version = "1.15.1", features = ["raw-window-handle-06", "unstable-winit-030"] }
i-slint-backend-winit = "1.15.1"
raw-window-handle = "0.6.2"
winit = "0.30.13"

sysinfo = "0.37.2"
windows = { version = "0.62.2", features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_System_Power",
    "Win32_UI_Controls",
    "Win32_Graphics_Gdi"
] }

[build-dependencies]
slint-build = "1.15.1"

[package.metadata.winresource]
ProductName = "Meter RS"
OriginalFilename = "meter-rs.exe"
LegalCopyright = "Copyright © 2025 Jaydar"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
