[package]
name = "Meter-rs"
version = "1.0.5"
edition = "2024"
build = "build.rs"
repository = "https://github.com/Jaydar/meter-rs"





[dependencies]
tokio = { version = "1.52.4", features = ["rt-multi-thread", "process","macros"] }
rayon = "1.12.0"
anyhow = "1.0.103"
slint = { version = "1.17.0", default-features = false, features = ["std", "compat-1-2", "renderer-software"] }
i-slint-backend-winit = { version = "1.17.0", default-features = false, features = ["renderer-software"] }
i-slint-backend-selector = { version = "1.17.0", default-features = false, features = ["unstable-winit-030", "renderer-software"] }
tray-icon = { version = "0.24.1", default-features = false }
muda = { version = "0.19.3", default-features = false }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "time"] }
tracing-appender = "0.2.5"
time = { version = "0.3.51", features = ["formatting", "macros"] }
config = { version = "0.15.25", default-features = false, features = ["yaml"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
resvg = "0.47.0"

raw-window-handle = "0.6.2"
winit = "0.30.13"
sysinfo = "0.39.5"
windows = { version = "0.62.2", features = [
    # "Win32_Security",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_Foundation",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_System_Power",
    "Win32_System_LibraryLoader",
    "Win32_UI_Controls",
    "Win32_Graphics_Gdi"
] }

[build-dependencies]
slint-build = "1.17.0"
winresource = "0.1.31"


[package.metadata.winresource]
ProductName = "Meter RS"
OriginalFilename = "meter-rs.exe"
LegalCopyright = "Copyright © 2025 Jaydar"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
