import { Theme } from "../../../theme.slint";
import "../../../assets/remixicon.ttf";

export component MenuItem inherits Rectangle {
    in property <string> icon;
    in property <string> text;
    in property <bool> checked;
    in property <bool> active: false;
    in property <bool> has_submenu: false;
    in-out property <bool> hover_fired: false;
    callback clicked <=> ta.clicked;
    callback hovered;

    height: 30px;
    border-radius: 6px;
    background: ta.has-hover ? Theme.menu-hover-bg : (root.active ? Theme.menu-active-bg : transparent);

    ta := TouchArea {
        mouse-cursor: MouseCursor.pointer;
        pointer-event(event) => {
            if (event.kind == PointerEventKind.move && ta.has-hover && !root.hover_fired) {
                root.hover_fired = true;
                root.hovered();
            }
        }

        changed has-hover => {
            if (!self.has-hover) {
                root.hover_fired = false;
            }
        }
    }

    HorizontalLayout {
        padding-left: 10px;
        padding-right: 10px;
        spacing: 8px;
        

        Text {
            width: 20px;
            font-size: 17px;
            font-family: "remixicon";
            text: root.checked ? "\u{eb7b}" : root.icon;
            color: (ta.has-hover || root.active) ? Theme.menu-hover-fg : Theme.text;
            vertical-alignment: center;
            horizontal-alignment: center;
        }

        Text {
            vertical-stretch: 1;
            text: root.text;
            color: (ta.has-hover || root.active) ? Theme.menu-hover-fg : Theme.text;
            vertical-alignment: center;
        }

        if (root.has_submenu) : Text {
            width: 20px;
            font-size: 15px;
            font-family: "remixicon";
            text: "\u{ea6d}";
            color: (ta.has-hover || root.active) ? Theme.menu-hover-fg : Theme.text;
            vertical-alignment: center;
            horizontal-alignment: right;
        }
    }
}
