import { AboutWindow } from "about.slint";
import { NormalWidget } from "widget/normal.slint";
import { SimpleWidget } from "widget/simple.slint";
import { Theme } from "../theme.slint";
import { ConfigStore, SnapMode } from "../config_store.slint";
import { DiskIoEntry, DiskMenuEntry, RuntimeStore } from "../runtime_store.slint";

export { AboutWindow, ConfigStore, DiskIoEntry, DiskMenuEntry, RuntimeStore, SnapMode, Theme }

export component AppWindow inherits Window {
    title: "Meter RS";

    always-on-top: root.always_on_top_state;

    no-frame: true;
    background: transparent;
    default-font-size: Theme.font-size;
    default-font-family: Theme.font-family;
    default-font-weight: Theme.font-weight;
    width: content.preferred-width;
    height: content.preferred-height;

    in-out property <bool> always_on_top_state: true;

    callback win_move(length, length);
    callback win_move_up();

    content := VerticalLayout {
        if (ConfigStore.simple_mode): SimpleWidget {
            win_move(x, y) => {
                root.win_move(x, y);
            }

            win_move_up => {
                root.win_move_up();
            }
        }

        if (!ConfigStore.simple_mode): NormalWidget {
            win_move(x, y) => {
                root.win_move(x, y);
            }

            win_move_up => {
                root.win_move_up();
            }
        }
    }
}
