import { AboutWindow } from "about.slint";
import { NormalWidget } from "widget/normal.slint";
import { SimpleWidget } from "widget/simple.slint";
import { Theme } from "../theme.slint";
import { ConfigStore, DisplayMode, SnapMode } from "../config_store.slint";
import { DiskIoEntry, DiskMenuEntry, RuntimeStore } from "../runtime_store.slint";

export { AboutWindow, ConfigStore, DiskIoEntry, DiskMenuEntry, RuntimeStore, DisplayMode, SnapMode, Theme }

export component AppWindow inherits Window {
    title: "Meter RS";

    always-on-top: root.always_on_top_state;

    no-frame: true;
    background: transparent;
    default-font-size: Theme.font-size;
    default-font-family: Theme.font-family;
    default-font-weight: Theme.font-weight;
    width: content.preferred-width;
    height: content.preferred-height + root.height_bias;

    in-out property <bool> always_on_top_state: true;
    in-out property <length> height_bias: 0px;

    callback win_move(length, length);
    callback win_move_up();

    content := VerticalLayout {
        if (ConfigStore.display_mode == DisplayMode.simple || ConfigStore.display_mode == DisplayMode.taskbar): SimpleWidget {
            win_move(x, y) => {
                root.win_move(x, y);
            }

            win_move_up => {
                root.win_move_up();
            }
        }

        if (ConfigStore.display_mode == DisplayMode.normal): NormalWidget {
            win_move(x, y) => {
                root.win_move(x, y);
            }

            win_move_up => {
                root.win_move_up();
            }
        }
    }
}
