import "../../assets/remixicon.ttf";
import { Theme } from "../../theme.slint";
import { MenuItem } from "widget/menu-item.slint";

export component MenuWindow inherits Window {
    width: 180px;
    height: content.preferred-height;
    // background: transparent;
    no-frame: true;
    always-on-top: true;

    in-out property <bool> auto_start_state: false;
    in-out property <bool> mouse_passthrough_state: false;
    in-out property <bool> prevent_sleep_state: false;
    in-out property <int> active_submenu: -1;

    callback close_menu();
    callback close_app();
    callback set_auto_start(bool);
    callback set_mouse_passthrough(bool);
    callback set_prevent_sleep(bool);
    callback turn_off_display();
    callback restart_explorer();
    callback clean_memory();
    callback show_theme_submenu(length, length);
    callback show_display_submenu(length, length);
    callback show_window_submenu(length, length);
    callback hide_submenu();
    callback show_about();

    content := Rectangle {
        width: 100%;
        height: 100%;
        border-radius: 10px;
        background: Theme.menu-bg;
        border-width: 1px;
        border-color: Theme.menu-border;
        // drop-shadow-blur: 14px;
        // clip: true;
        VerticalLayout {
            padding: 8px;
            spacing: 2px;

            theme_item := MenuItem {
                text: "主题";
                icon: "\u{eeaa}";
                has_submenu: true;
                active: root.active_submenu == 0;
                hovered => {
                    root.active_submenu = 0;
                    root.show_theme_submenu(theme_item.x, theme_item.y);
                }
            }

            display_item := MenuItem {
                text: "显示设置";
                icon: "\u{ef72}";
                has_submenu: true;
                active: root.active_submenu == 1;
                hovered => {
                    root.active_submenu = 1;
                    root.show_display_submenu(display_item.x, display_item.y);
                }
            }

            window_item := MenuItem {
                text: "窗口";
                icon: "\u{f1d9}";
                has_submenu: true;
                active: root.active_submenu == 2;
                hovered => {
                    root.active_submenu = 2;
                    root.show_window_submenu(window_item.x, window_item.y);
                }
            }

            Rectangle {
                height: 1px;
                background: Theme.menu-border;
            }

            MenuItem {
                text: "鼠标穿透";
                checked: root.mouse_passthrough_state;
                hovered => {
                    root.active_submenu = -1;
                    root.hide_submenu();
                }
                clicked => {
                    root.mouse_passthrough_state = !root.mouse_passthrough_state;
                    root.set_mouse_passthrough(root.mouse_passthrough_state);
                    root.close_menu();
                }
            }

            MenuItem {
                text: "禁止休眠";
                checked: root.prevent_sleep_state;
                hovered => {
                    root.active_submenu = -1;
                    root.hide_submenu();
                }
                clicked => {
                    root.prevent_sleep_state = !root.prevent_sleep_state;
                    root.set_prevent_sleep(root.prevent_sleep_state);
                    root.close_menu();
                }
            }

            MenuItem {
                text: "开机自启";
                checked: root.auto_start_state;
                hovered => {
                    root.active_submenu = -1;
                    root.hide_submenu();
                }
                clicked => {
                    root.auto_start_state = !root.auto_start_state;
                    root.set_auto_start(root.auto_start_state);
                    root.close_menu();
                }
            }

            MenuItem {
                text: "关闭显示器";
                hovered => {
                    root.active_submenu = -1;
                    root.hide_submenu();
                }
                clicked => {
                    root.turn_off_display();
                    root.close_menu();
                }
            }

            MenuItem {
                text: "重启资源管理器";
                hovered => {
                    root.active_submenu = -1;
                    root.hide_submenu();
                }
                clicked => {
                    root.restart_explorer();
                    root.close_menu();
                }
            }

            MenuItem {
                text: "内存清理";
                hovered => {
                    root.active_submenu = -1;
                    root.hide_submenu();
                }
                clicked => {
                    root.clean_memory();
                    root.close_menu();
                }
            }

            Rectangle {
                height: 1px;
                background: Theme.menu-border;
            }

            MenuItem {
                text: "关于 Meter RS";
                icon: "\u{ec51}";
                hovered => {
                    root.active_submenu = -1;
                    root.hide_submenu();
                }
                clicked => {
                    root.show_about();
                    root.close_menu();
                }
            }

            MenuItem {
                text: "退出程序";
                icon: "\u{f1af}";
                hovered => {
                    root.active_submenu = -1;
                    root.hide_submenu();
                }
                clicked => {
                    root.close_app();
                }
            }
        }
    }
}
