import { Theme } from "../../theme.slint";
import { Store } from "../../store.slint";
import { MenuItem } from "widget/menu-item.slint";

export component Menu3Window inherits Window {
    width: 180px;
    height: content.preferred-height;
    background: transparent;
    no-frame: true;
    always-on-top: true;

    callback close_menu();
    callback toggle_disk(string);

    Rectangle {
        width: 180px;
        height: 100%;
        border-radius: 10px;
        background: Theme.menu-bg;
        border-width: 1px;
        border-color: Theme.menu-border;
        drop-shadow-blur: 14px;

        content := VerticalLayout {
            padding: 8px;
            spacing: 2px;

            for entry in Store.disk_menu_entries : MenuItem {
                text: entry.name;
                checked: entry.checked;
                clicked => {
                    root.toggle_disk(entry.id);
                    root.close_menu();
                }
            }
        }
    }
}







