import { Theme } from "theme.slint";
import { DiskMenuEntry } from "store.slint";
import { MenuItem } from "widget/menu-item.slint";

export component DiskMenuWindow inherits Window {
    width: 220px;
    height: content.preferred-height;
    background: transparent;
    no-frame: true;
    always-on-top: true;

    in-out property <[DiskMenuEntry]> entries: [];

    callback close_menu();
    callback toggle_disk(string);

    Rectangle {
        width: 100%;
        height: 100%;
        border-radius: 10px;
        background: Theme.menu-bg;
        border-width: 1px;
        border-color: Theme.menu-border;
        drop-shadow-blur: 14px;

        content := VerticalLayout {
            padding: 8px;
            spacing: 2px;

            for entry in root.entries : MenuItem {
                text: entry.name;
                checked: entry.checked;
                clicked => {
                    root.toggle_disk(entry.id);
                    root.close_menu();
                }
            }
        }
    }
}
