import { Theme } from "theme.slint";
import { Button, Palette } from "std-widgets.slint";

export component RightMenu {
    width: 100%;
    height: 100%;
    
    ContextMenuArea {
        Menu {
            MenuItem {
                title: "总是置顶";
                activated => {
                    debug("Cut");
                }
            }

            MenuItem {
                title: "自动吸附";
                activated => {
                    debug("Copy");
                }
            }

            MenuItem {
                title: @tr("更多设置");
                activated => {
                    debug("Paste");
                }
            }

            MenuSeparator { }

            Menu {
                title: "关于 mon-rs";
            }

            Menu {
                title: "退出";
            }
        }
    }
}
