export struct DiskIoEntry {
    id: string,
    name: string,
    usage: float,
    read: string,
    write: string,
}

export struct DiskMenuEntry {
    id: string,
    name: string,
    checked: bool,
}

export struct NetworkAdapterEntry {
    id: string,
    name: string,
    current_mac: string,
    mac: string,
}

export struct RouteEntry {
    destination: string,
    adapter_id: string,
    interface_index: string,
    adapter: string,
    gateway: string,
    metric: string,
    source: string,
}

export global RuntimeStore {
    in-out property <length> taskbar_height: 40px;
    in-out property <float> cpu_usage: 0;
    in-out property <float> memory_usage: 0;
    in-out property <float> disk_usage: 0;
    in-out property <string> disk_total_read: "0.00 KB";
    in-out property <string> disk_total_write: "0.00 KB";
    in-out property <string> network_rx: "0.00 KB";
    in-out property <string> network_tx: "0.00 KB";
    in-out property <[DiskIoEntry]> monitored_disks: [];
    in-out property <string> computer_name: "Unknown";
    in-out property <[DiskMenuEntry]> disk_menu_entries: [];
    in-out property <bool> has_monitored_disks: false;
}
