export global Theme {
    in property <color> window-bg: #000000E6;
    in property <color> card-bg: #0A0F1C;
    in property <color> title: #00E5FF;
    in property <color> sub-title: #00B8D4;

    in property <color> text: #FFFFFF;
    in property <color> text-low: #00E676;
    in property <color> text-mid: #FFEA00;
    in property <color> text-high: #FF1744;

    in property <string> font-family: "Microsoft YaHei UI";
    in property <int> font-weight: 700;
    in property <length> font-size: 10pt;
}
